name: Frontend CI (React Native + Expo)

# Trigger on pull requests to main and pushes to main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # ─── 1) BUILD & TEST ────────────────────────────────────────────────────────────
  build-and-test:
    name: Build & Test (Node 18, Expo)
    runs-on: ubuntu-latest

    steps:
      # 1.1 Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 1.2 Set up Node.js 18
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      # 1.3 Install dependencies (npm lockfile)
      - name: Install dependencies
        run: npm ci

      # 1.4 Run ESLint (static analysis)
      - name: Run ESLint
        run: npm run lint
        # Assumes "lint" script in package.json. Fails on any lint errors.

      # 1.5 Run unit tests (Jest or similar)
      - name: Run unit tests
        run: npm test
        # Assumes "test" script in package.json.

      # 1.6 Dependency vulnerability check
      - name: Run npm audit
        run: npm audit --audit-level=moderate
        # Fails if any vulnerability ≥ moderate. Adjust level as needed.

      # 1.7 Build Expo Web (validates bundler)
      - name: Build Expo Web
        run: npm run build:web
        # Assumes "build:web" in package.json calls `expo build:web`.
        # This produces a `web-build/` directory by default.

      # 1.8 Upload the web-build folder as an artifact
      - name: Upload web-build artifact
        uses: actions/upload-artifact@v3
        with:
          name: expo-web-build
          path: web-build
          # This allows you (or downstream jobs) to download the compiled web bundle.

  # ─── 2) CODEQL SECURITY SCAN ─────────────────────────────────────────────────────
  codeql-analysis:
    name: CodeQL Security Scan (JavaScript/TypeScript)
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
